/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AppBottomBar: typeof import('./../components/AppBottomBar.vue')['default']
    AppLeftBar: typeof import('./../components/AppLeftBar.vue')['default']
    AppTopBar: typeof import('./../components/AppTopBar.vue')['default']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    BilladmButton: typeof import('./../components/common/BilladmButton.vue')['default']
    BilladmCategoryTagSetting: typeof import('./../components/settings_view/BilladmCategoryTagSetting.vue')['default']
    BilladmChart: typeof import('./../components/da_view/BilladmChart.vue')['default']
    BilladmChartList: typeof import('./../components/da_view/BilladmChartList.vue')['default']
    BilladmChartView: typeof import('./../components/da_view/BilladmChartView.vue')['default']
    BilladmFileSelect: typeof import('./../components/BilladmFileSelect.vue')['default']
    BilladmFullScreen: typeof import('./../components/common/BilladmFullScreen.vue')['default']
    BilladmLedgerSelect: typeof import('./../components/BilladmLedgerSelect.vue')['default']
    BilladmModal: typeof import('./../components/common/BilladmModal.vue')['default']
    BilladmStatisticsFooter: typeof import('./../components/common/BilladmStatisticsFooter.vue')['default']
    BilladmTimeRangePicker: typeof import('./../components/common/BilladmTimeRangePicker.vue')['default']
    CategoryTagPanel: typeof import('./../components/settings_view/CategoryTagPanel.vue')['default']
    DataAnalysisView: typeof import('./../components/da_view/DataAnalysisView.vue')['default']
    DataImportExportSetting: typeof import('./../components/settings_view/DataImportExportSetting.vue')['default']
    Layout: typeof import('./../components/Layout.vue')['default']
    LedgerView: typeof import('./../components/ledger_view/LedgerView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./../components/settings_view/SettingsView.vue')['default']
    TransactionRecordFilter: typeof import('./../components/common/TransactionRecordFilter.vue')['default']
    TransactionRecordTable: typeof import('./../components/tr_view/TransactionRecordTable.vue')['default']
    TransactionRecordView: typeof import('./../components/tr_view/TransactionRecordView.vue')['default']
    WorkspaceSetting: typeof import('./../components/settings_view/WorkspaceSetting.vue')['default']
  }
}
