/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardGrid: typeof import('ant-design-vue/es')['CardGrid']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/es')['Col']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AppLeftBar: typeof import('./../components/AppLeftBar.vue')['default']
    AppTopBar: typeof import('./../components/AppTopBar.vue')['default']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    BilladmCategoryTagSetting: typeof import('./../components/settings_view/BilladmCategoryTagSetting.vue')['default']
    BilladmChart: typeof import('./../components/da_view/BilladmChart.vue')['default']
    BilladmChartDisplay: typeof import('./../components/da_view/BilladmChartDisplay.vue')['default']
    BilladmChartPanel: typeof import('./../components/da_view/BilladmChartPanel.vue')['default']
    BilladmFileSelect: typeof import('./../components/BilladmFileSelect.vue')['default']
    BilladmFullScreen: typeof import('./../components/common/BilladmFullScreen.vue')['default']
    BilladmLedgerSelect: typeof import('./../components/BilladmLedgerSelect.vue')['default']
    BilladmStatisticsFooter: typeof import('./../components/common/BilladmStatisticsFooter.vue')['default']
    BilladmTimeRangePicker: typeof import('./../components/common/BilladmTimeRangePicker.vue')['default']
    DataAnalysisView: typeof import('./../components/da_view/DataAnalysisView.vue')['default']
    Layout: typeof import('./../components/Layout.vue')['default']
    LedgerView: typeof import('./../components/ledger_view/LedgerView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./../components/settings_view/SettingsView.vue')['default']
    TransactionRecordFilter: typeof import('./../components/common/TransactionRecordFilter.vue')['default']
    TransactionRecordTable: typeof import('./../components/tr_view/TransactionRecordTable.vue')['default']
    TransactionRecordView: typeof import('./../components/tr_view/TransactionRecordView.vue')['default']
  }
}
